services:
  ai-app:
    container_name: ai-app
    build: .
    command: bash -c "uvicorn main:app --host 0.0.0.0 --port 8000"
    volumes:
      - .:/ai-app
    ports:
      - 8002:8000
    restart: always